baseURL: https://michaellefkowitz.netlify.app/
languageCode: en-us
title: Portfolio website for Ryan Wang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: An Introduction
    subtitle: |-
      Hello,
    title: My name is Michael Lefkowitz and I'm a masters in financial analysis 
    student interested in finance.
  blog: {}
  contact: 
    address:
      - city: London,
        country: UK
        street: xxxx
        title: xxxx
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mlefkowitz.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +xx x xxx xxx xxxx
        title: Phone
  custom_css: []
  custom_js: []
  description: Masters in Financial Analysis
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Michael
    enable: yes
    quicklinks:
      - alt: CA09 AUT21 Data Analytics for Finance
        text: 'Course: '
        url: https://www.html5up.net
    social:
#     - icon: fa-twitter
#       label: Twitter
#       url: https://www.twitter.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/michael_lefty/
      - icon: fa-github
        label: GitHub
        url: https://github.com/michaellefkowitz1
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/michael-lefkowitz1/
  image: ''
  name: Michael Lefkowitz
  navigation:
#    button1:
#      - name: Get Started
#        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Back to Homepage
        url: '#'
#      - name: Blogs
#        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By Michael Lefkowitz
    title: Professional Website
  tiles:
    enable: yes
    showcase:
       - image: lbs.jpg
         subtitle: London Business School
         title: Education 
         url: blogs/lbs
       - image: resume.jpg
         subtitle: Investment Banking Recruitment
         title: My Resume
         url: blogs/resume
       - image: ph.jpg
#        subtitle: Lorem Etiam Nullam
         title: Professional Headshot
         url: blogs/ph
       - image: corporate.jpg
         subtitle: Past experience and future plans
         title: Career
         url: blogs/corporate
       - image: pic05.jpg
         subtitle: Risk and Return Analysis
         title: R Project
         url: blogs/risk_return
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
#    buttonText: Get Started
#    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs